apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: kubevirt
data:
  nginx.conf: |
    worker_processes  3;
    pid /tmp/nginx.pid;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8080;
          server_name  _;
          location / {}
      }
    }
