apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: kubevirt
  labels:
    app: http-server
spec:
  selector:
    matchLabels:
      app: http-server
  replicas: 1
  template:
    metadata:
      labels:
        app: http-server
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-conf
        - name: iso-dv
          persistentVolumeClaim:
            claimName: iso-dv
      containers:
      - name: http-server
        image: nginxinc/nginx-unprivileged:latest
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: "/etc/nginx/html"
            name: iso-dv
          - mountPath: "/etc/nginx/nginx.conf"
            subPath: nginx.conf
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: http-server
  namespace: kubevirt
  labels:
    app: http-server
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: http-server
